server.port=8082
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bridge_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:Abi@06012003}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
app.transport=${APP_TRANSPORT:rest}
app.ibs-url=${IBS_URL:http://localhost:8083}
app.airline-url=${AIRLINE_URL:http://localhost:8081}
bridge.timeout-seconds=60
spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:9092}
spring.kafka.consumer.auto-offset-reset=latest
